name: Client Application

on:
    push:
        branches: [main]
        paths: ['apps/client/**']
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build-client:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Cloning Repository
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Dependencies
              run: npm ci --production

            - name: Run Client Test Cases
              run: npm run test:client

            - name: Build Client Application
              run: npm run build:client

            - uses: amondnet/vercel-action@v25 #deploy
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
                  vercel-args: '--prod' #Optional
                  working-directory: ./dist/apps/client
