name: Deploy Client Application

on:
    push:
        branches: [main]
        paths: ['apps/client/**']
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build-client:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Cloning Repository
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Dependencies
              run: npm ci --production

            - name: Run Client Test Cases
              run: npm run test:client

            - name: Build Client Application
              run: npm run build:client

            # - name: Deploy
            #   uses: JamesIves/github-pages-deploy-action@v4.3.4
            #   with:
            #       folder: dist/apps/client
            #       branch: gh-pages
